### PR TITLE
True promise OR callback refactor

### PR DESCRIPTION
**Pull request by vernak2539**
- updated auth client
- refactored promise integration
- added/updated tests
- slimmed dependencies

### CODE REVIEW

**Comment by dougwilson** [comment]
Looks like the failure is from a missing dependency.

**Comment by vernak2539** [comment]
Yep, hopefully the new push works

**Comment by vernak2539** [comment]
@dougwilson all the tests are passing. mind taking a look? 

Future work will include refactoring the tests and such, but I think they've been modified in the correct way, and I've tested a few scenarios.

**Comment by dougwilson** [comment]
Changes seem fine to me.

**Comment by dougwilson** [comment]
Because this used to technically always return a promise, even if a callback was provided, I'm leaning towards releasing this as 2.0.0. It'll match fuel-auth as well. @vernak2539

**Comment by vernak2539** [comment]
Sounds close enough to a breaking change. Go for it

**Pull request merged**
